//! `.Lb` library names (mdoc(7)): each library mandoc describes, and its text. Recorded by
//! rendering candidate names through `mandoc -T utf8`; a library not listed prints as
//! `library “name”`.

pub static LIBRARIES: &[(&str, &str)] = &[
    ("lib80211", "802.11 Wireless Network Management Library (lib80211, -l80211)"),
    ("libalias", "Packet Aliasing Library (libalias, -lalias)"),
    ("libarchive", "Streaming Archive Library (libarchive, -larchive)"),
    ("libarm", "ARM Architecture Library (libarm, -larm)"),
    ("libbluetooth", "Bluetooth Library (libbluetooth, -lbluetooth)"),
    ("libbsdxml", "eXpat XML parser library (libbsdxml, -lbsdxml)"),
    ("libbsm", "Basic Security Module Library (libbsm, -lbsm)"),
    ("libc", "Standard C Library (libc, -lc)"),
    ("libc_r", "Reentrant C Library (libc_r, -lc_r)"),
    ("libcalendar", "Calendar Arithmetic Library (libcalendar, -lcalendar)"),
    ("libcam", "Common Access Method User Library (libcam, -lcam)"),
    ("libcasper", "Casper Library (libcasper, -lcasper)"),
    ("libcompat", "Compatibility Library (libcompat, -lcompat)"),
    ("libcrypt", "Crypt Library (libcrypt, -lcrypt)"),
    ("libcurses", "Curses Library (libcurses, -lcurses)"),
    ("libcuse", "Userland Character Device Library (libcuse, -lcuse)"),
    ("libdevinfo", "Device and Resource Information Utility Library (libdevinfo, -ldevinfo)"),
    ("libdevstat", "Device Statistics Library (libdevstat, -ldevstat)"),
    ("libdl", "Dynamic Linker Services Filter (libdl, -ldl)"),
    ("libdwarf", "DWARF Access Library (libdwarf, -ldwarf)"),
    ("libedit", "Command Line Editor Library (libedit, -ledit)"),
    ("libelf", "ELF Access Library (libelf, -lelf)"),
    ("libevent", "Event Notification Library (libevent, -levent)"),
    ("libexecinfo", "Backtrace Information Library (libexecinfo, -lexecinfo)"),
    ("libfetch", "File Transfer Library (libfetch, -lfetch)"),
    ("libform", "Curses Form Library (libform, -lform)"),
    ("libgeom", "Userland API Library for Kernel GEOM subsystem (libgeom, -lgeom)"),
    ("libgpio", "General-Purpose Input Output (GPIO) library (libgpio, -lgpio)"),
    ("libi386", "i386 Architecture Library (libi386, -li386)"),
    ("libintl", "Internationalized Message Handling Library (libintl, -lintl)"),
    ("libipsec", "IPsec Policy Control Library (libipsec, -lipsec)"),
    ("libjail", "Jail Library (libjail, -ljail)"),
    ("libkiconv", "Kernel-side iconv Library (libkiconv, -lkiconv)"),
    ("libkse", "N:M Threading Library (libkse, -lkse)"),
    ("libkvm", "Kernel Data Access Library (libkvm, -lkvm)"),
    ("libm", "Math Library (libm, -lm)"),
    ("libm68k", "m68k Architecture Library (libm68k, -lm68k)"),
    ("libmagic", "Magic Number Recognition Library (libmagic, -lmagic)"),
    ("libmandoc", "Mandoc Macro Compiler Library (libmandoc, -lmandoc)"),
    ("libmd", "Message Digest (MD4, MD5, etc.) Support Library (libmd, -lmd)"),
    ("libmemstat", "Kernel Memory Allocator Statistics Library (libmemstat, -lmemstat)"),
    ("libmenu", "Curses Menu Library (libmenu, -lmenu)"),
    ("libnetgraph", "Netgraph User Library (libnetgraph, -lnetgraph)"),
    ("libnv", "Name/value pairs library (libnv, -lnv)"),
    ("libossaudio", "OSS Audio Emulation Library (libossaudio, -lossaudio)"),
    ("libpam", "Pluggable Authentication Module Library (libpam, -lpam)"),
    ("libpanel", "Z-order for curses windows (libpanel, -lpanel)"),
    ("libpcap", "Packet capture Library (libpcap, -lpcap)"),
    ("libpmc", "Performance Counters Library (libpmc, -lpmc)"),
    ("libprocstat", "Process and Files Information Retrieval (libprocstat, -lprocstat)"),
    ("libpthread", "POSIX Threads Library (libpthread, -lpthread)"),
    ("libradius", "RADIUS Client Library (libradius, -lradius)"),
    ("librpcsec_gss", "RPC GSS-API Authentication Library (librpcsec_gss, -lrpcsec_gss)"),
    ("librt", "POSIX Real-time Library (librt, -lrt)"),
    ("libsbuf", "Safe String Composition Library (libsbuf, -lsbuf)"),
    ("libsdp", "Bluetooth Service Discovery Protocol User Library (libsdp, -lsdp)"),
    ("libstdthreads", "C11 Threads Library (libstdthreads, -lstdthreads)"),
    ("libsysdecode", "System Argument Decoding Library (libsysdecode, -lsysdecode)"),
    ("libtacplus", "TACACS+ Client Library (libtacplus, -ltacplus)"),
    ("libtermcap", "Termcap Access Library (libtermcap, -ltermcap)"),
    ("libterminfo", "Terminal Information Library (libterminfo, -lterminfo)"),
    ("libthr", "1:1 Threading Library (libthr, -lthr)"),
    ("libufs", "UFS File System Access Library (libufs, -lufs)"),
    ("libugidfw", "File System Firewall Interface Library (libugidfw, -lugidfw)"),
    ("libulog", "User Login Record Library (libulog, -lulog)"),
    ("libutil", "System Utilities Library (libutil, -lutil)"),
    ("libvgl", "Video Graphics Library (libvgl, -lvgl)"),
    ("libxo", "Text, XML, JSON, and HTML Output Emission Library (libxo, -lxo)"),
    ("libz", "Compression Library (libz, -lz)"),
];

/// The text for `.Lb name`.
pub fn name(lib: &str) -> String {
    match LIBRARIES.iter().find(|(l, _)| *l == lib) {
        Some((_, text)) => text.to_string(),
        None => format!("library \u{201C}{lib}\u{201D}"),
    }
}
