//! Multiboot2 boot path: the Multiboot2 header, a real 32-bit-protected-mode-to-64-bit-long-mode
//! bootstrap trampoline, Multiboot2 info-tag parsing, and the final page tables -- everything
//! needed to reach the exact same `oxidebsd::init(&BootInfo)` entry point the Limine boot path
//! reaches, from a completely different (and much more primitive) starting CPU state. See
//! CLAUDE.md's Multiboot2 section for the full design/staging.
//!
//! **Why this needs its own from-scratch trampoline, not a header tweak**: regardless of loader --
//! real GRUB, or Limine's own vendored `protocol: multiboot2` support -- the CPU handoff for a
//! Multiboot2 kernel lands in 32-bit protected mode, paging disabled, a minimal/undefined GDT (see
//! the Multiboot2 spec's "Machine state" section) -- nothing like the 64-bit long mode with paging
//! and an HHDM already active that `limine_entry_point!`'s `kmain` gets to assume.
//!
//! **Two-stage trampoline**, matching this codebase's existing convention of a tiny hand-rolled
//! asm stub handing off to ordinary Rust as soon as possible (see `sys/process/fault_trampoline.rs`
//! /`context_switch.rs`'s own `global_asm!` blocks for precedent):
//! - Stage A (`global_asm!`, below), **two entry points**: `_start32` -- reads the real classic
//!   Multiboot2 handoff registers (`EAX`=magic, `EBX`=info-structure physical address), sets up a
//!   small stack, loads a minimal flat 32-bit GDT (the loader's own GDT contents are spec-
//!   undefined past entry), builds temporary page tables, enables PAE/`EFER.LME`/`CR0.PG`, and
//!   far-jumps into 64-bit mode at `_start64_prelim`. `_efi64_start` is a second, EFI-only entry
//!   point (spec's EFI64 entry-address header tag) real GRUB uses instead of `_start32` when it's
//!   itself running under UEFI -- see that label's own doc comment for why it exists at all (a
//!   real GRUB/OVMF bug, confirmed via an isolated repro, in the classic entry's 64-to-32-bit
//!   downgrade specifically). Both converge on the same `mb2_enter_rust` tail, which jumps into
//!   ordinary Rust (`multiboot2_rust_entry`, generated by the `multiboot2_entry_point!` macro
//!   below).
//! - Stage B (ordinary Rust, `init_from_mbi`): validates the magic, parses the Multiboot2 memory
//!   map into the exact same `limine::memmap::Entry` shape `boot::BootInfo`/
//!   `memory::BootInfoFrameAllocator` already consume, builds a real *final* set of page tables
//!   (reusing Stage A's own kernel-image mapping, plus a fresh HHDM-style window), installs them
//!   via `Cr3::write`, and returns a `&'static BootInfo` -- from here on, completely
//!   indistinguishable from the Limine boot path, regardless of which Stage A entry point was
//!   used to get here.
//!
//! **Temporary vs. final page tables, and why the "low identity" and "kernel higher-half"
//! windows are sized completely differently**: the *low* identity window (`temp_pd_low`) only
//! needs to cover early low-memory boot structures (the trampoline's own code, and wherever
//! GRUB/Limine placed the Multiboot2 info structure -- always well under a few MiB in practice),
//! so a fixed, generous 64 MiB constant is fine and never goes stale. The *kernel higher-half*
//! window (`temp_pd_high`, reused directly by the final tables -- see `install_final_page_tables`)
//! has to cover the kernel's own **entire loaded image**, which is a completely different scale:
//! this kernel's own embedded BusyBox/musl/Clang+LLVM/POSIX-conformance-corpus content
//! makes `.rodata` alone upward of 100 MiB already (confirmed via `readelf -l` against a real
//! release build) and grows over time -- the exact "embedded corpus outgrew a fixed constant"
//! class of bug CLAUDE.md documents hitting the userland-load-base floor repeatedly. That window
//! is therefore sized dynamically, at boot, from the linker-provided `_kernel_phys_start`/
//! `_kernel_phys_end` symbols (see `x86_64-oxidebsd-multiboot2.ld`), never a hardcoded page count.

use core::arch::global_asm;
use core::mem::MaybeUninit;

use limine::memmap::{
    Entry, MEMMAP_ACPI_NVS, MEMMAP_ACPI_RECLAIMABLE, MEMMAP_BAD_MEMORY, MEMMAP_RESERVED,
    MEMMAP_USABLE,
};
use x86_64::PhysAddr;
use x86_64::registers::control::Cr3;
use x86_64::structures::paging::{PageTable, PageTableFlags, PhysFrame};

use super::BootInfo;

/// Multiboot2 spec magic values (Multiboot2 spec section 3 "OS image format" / section 5.2 "Machine
/// state"). The header magic/architecture/checksum themselves live in the `global_asm!` block
/// below now, not as Rust constants -- see that block's own doc comment for why.
const MULTIBOOT2_BOOTLOADER_MAGIC: u32 = 0x36d7_6289;

const TAG_TYPE_END: u32 = 0;
const TAG_TYPE_MMAP: u32 = 6;
const TAG_TYPE_FRAMEBUFFER: u32 = 8;

/// Multiboot2 framebuffer info tag's own `framebuffer_type` field (spec section 3.6.9) -- the only
/// one `parse_mmap` below understands. `0` (indexed/palette) and `2` (EGA text) are real,
/// documented alternatives no real UEFI/BIOS+QEMU or real hardware GOP/VBE framebuffer this
/// project targets actually reports -- left unhandled (no `FbInfo` populated, `console::
/// framebuffer` stays a no-op) rather than guessed at.
const FRAMEBUFFER_TYPE_RGB: u8 = 1;

/// Multiboot2 memory-map entry `type` field values (spec section 3.6.8).
const MULTIBOOT_MEMORY_AVAILABLE: u32 = 1;
const MULTIBOOT_MEMORY_ACPI_RECLAIMABLE: u32 = 3;
const MULTIBOOT_MEMORY_NVS: u32 = 4;
const MULTIBOOT_MEMORY_BADRAM: u32 = 5;
// MULTIBOOT_MEMORY_RESERVED (2) and any value this spec hasn't defined yet both fall through to
// the same MEMMAP_RESERVED translation below -- see `translate_mmap_type`.

const HUGE_PAGE_SIZE: u64 = 0x20_0000; // 2 MiB
const ONE_GIB: u64 = 0x4000_0000;

/// Physical load address of the Stage A trampoline (`. = 0x100000` in
/// `x86_64-oxidebsd-multiboot2.ld`) -- must stay in sync with that linker script. Used, alongside
/// `_kernel_phys_end`, to carve the kernel's own real physical footprint out of the "usable"
/// memory-map entries handed to `memory::BootInfoFrameAllocator` (see `exclude_kernel_range`'s own
/// doc comment for why this is required at all, unlike the Limine boot path).
const BOOT32_TRAMPOLINE_PHYS_BASE: u64 = 0x100000;

/// Same fixed higher-half base the plain-Limine kernel linker script already uses -- see
/// `x86_64-oxidebsd-multiboot2.ld`'s own doc comment for why `.text`/etc. keep this exact VMA.
const KERNEL_HIGHER_HALF_BASE: u64 = 0xffff_ffff_8000_0000;

/// A fixed HHDM-style offset for the Multiboot2 boot path, distinct from whatever value Limine
/// happens to pick for its own HHDM -- this path builds its own final page tables from scratch, so
/// nothing requires matching Limine's exact offset, only that `boot::BootInfo::
/// physical_memory_offset` and the mapping installed by `install_final_page_tables` agree.
pub const MULTIBOOT2_HHDM_OFFSET: u64 = 0xffff_8000_0000_0000;

/// Real ceiling for the HHDM window this boot path installs, matching `scripts/qemu_runner.sh`'s
/// `-m 8192`. A documented, deliberate scope limit versus Limine's full-range HHDM (which sizes
/// itself off the bootloader's own memory-map response) -- nothing at this point in boot has
/// parsed the real memory map yet (building that map is literally what this code is doing), so a
/// fixed ceiling is used instead, same simplification the real ceiling on the mmap-entry array
/// below already makes.
const MULTIBOOT2_HHDM_CEILING_BYTES: u64 = 8 * 1024 * 1024 * 1024;
const HHDM_PD_COUNT: usize = (MULTIBOOT2_HHDM_CEILING_BYTES / ONE_GIB) as usize;

unsafe extern "C" {
    /// Provided by `x86_64-oxidebsd-multiboot2.ld`: the physical load address of the main kernel
    /// image (`.text` onward -- *not* including the tiny `boot32` trampoline before it) and one
    /// past its end. Only ever used for their *addresses* (via `&raw const`), never dereferenced --
    /// the classic "linker symbol as an opaque address marker" idiom.
    static _kernel_phys_start: u8;
    static _kernel_phys_end: u8;
    /// Defined in the `global_asm!` block below: the physical addresses of the temporary kernel
    /// higher-half and low-identity PDPTs Stage A already built. Both are reused as-is by
    /// `install_final_page_tables` -- their content doesn't change between the temporary and final
    /// address spaces. The low-identity window in particular is *not* optional to carry over: the
    /// currently-executing call stack (`boot32_stack`, still in active use all the way from Stage
    /// A through `oxidebsd::init` and beyond -- nothing switches to a "real" kernel stack this
    /// early) lives inside it, so dropping it out from under the very stack the CPU is running on
    /// faults on the first instruction (typically a `ret`) that touches the stack after `CR3` is
    /// reloaded. Found live: everything up through the `Cr3::write` call itself succeeded, but
    /// execution never returned from `install_final_page_tables` -- a real, silent triple fault
    /// (no IDT exists yet at this point in boot), not a Rust panic.
    static temp_pdpt_high: u8;
    static temp_pdpt_low: u8;
}

/// Converts a virtual address inside the kernel's own higher-half image (`.text`/`.rodata`/
/// `.data`/`.bss` -- anything compiled as part of this crate, `#[link_section]`-tagged
/// `.boot32.*` statics excluded) to the physical address backing it, using the constant
/// relationship `x86_64-oxidebsd-multiboot2.ld`'s `AT()` placement guarantees: every one of those
/// sections has VMA `KERNEL_HIGHER_HALF_BASE + k` and LMA `_kernel_phys_start + k`, for the same
/// `k`, regardless of section.
fn kernel_virt_to_phys(virt: u64) -> u64 {
    let kernel_phys_start = (&raw const _kernel_phys_start) as u64;
    virt - KERNEL_HIGHER_HALF_BASE + kernel_phys_start
}

// The Multiboot2 header itself, Stage A's 32-bit-protected-mode entry point, and the new EFI64
// entry point all live in this one `global_asm!` block. Intel syntax throughout, matching every
// other `global_asm!` block in this codebase.
//
// **The header lives in asm, not as a Rust `static` struct** (an earlier version of this file did
// exactly that) -- the EFI64 entry-address tag below (see `_efi64_start`'s own doc comment) has to
// embed that symbol's own address as a plain 32-bit field, and Rust has no stable, supported way
// to bake a function's link-time address into an integer field of a `static` initializer (only
// pointer-*typed* statics get that treatment). Plain `.long _efi64_start` in asm is a completely
// ordinary link-time relocation, no such restriction -- the same technique `far_ptr_flush`/
// `far_ptr_long_mode` below already use for the same reason. `header_length`/the checksum are
// computed as real assembler constant expressions (`header_end - header_start`, and the checksum
// arithmetic over two other compile-time-known values), not hand-computed by a human.
//
// Register conservation note: `EAX`/`EBX` (the real classic-entry Multiboot2 handoff registers)
// are stashed to memory immediately, before anything else touches them -- the temporary-page-
// table-building code below needs `EAX`/`EBX`/`ECX`/`EDX`/`ESI`/`EDI` freely as scratch.
//
// Far jumps use an indirect `jmp far ptr [mem]` through a small 6-byte offset:selector structure
// rather than a direct `jmp sel:label` immediate -- LLVM's integrated assembler (Intel dialect)
// rejects the latter's `sel:label` operand syntax outright ("unexpected token in argument list").
global_asm!(
    // `.pushsection` here, `.popsection` at the very end: every later `.section` switch in this
    // block (bss/data/text) only rewrites the pushed entry, and the pop restores whatever section
    // was active before. rustc concatenates a codegen unit's `global_asm!` blocks, so without this
    // the block ended in `.boot32.text` and any section-less asm after it inherited that --
    // found live: the syscall entry stub (`sys/syscall/mod.rs`) landed in `.boot32.text`, 2 GiB
    // from the higher-half kernel, and `multiboot2-boot-smoke` failed to link with
    // `R_X86_64_PLT32 out of range` as soon as an unrelated code change reshuffled the CGUs.
    //
    // Must land within the file's first 32 KiB and be 8-byte aligned -- guaranteed here by
    // x86_64-oxidebsd-multiboot2.ld placing .multiboot_header first, right after `. = 0x100000`.
    ".pushsection .multiboot_header, \"a\"",
    ".align 8",
    "mb2_header_start:",
    ".long 0xe85250d6",                        // magic
    ".long 0",                                 // architecture (0 = i386/protected-mode)
    ".long mb2_header_end - mb2_header_start", // header_length
    // Real Multiboot2 checksum rule: magic + architecture + header_length + checksum == 0 (mod
    // 2^32). Only covers these four base-header fields, not any tag that follows.
    ".long -(0xe85250d6 + 0 + (mb2_header_end - mb2_header_start))",
    // "EFI boot services" tag (type 7, bare marker -- no extra payload beyond the 8-byte tag
    // header itself). Tells an EFI-aware loader not to call `ExitBootServices()` before jumping to
    // us. Found necessary by disassembling real GRUB's own compiled multiboot2.mod: its boot
    // dispatch reads a `grub_efi_is_finished` flag to choose between `grub_relocator64_efi_boot`
    // (genuine 64-bit EFI-native handoff) and `grub_relocator32_boot` (the classic 32-bit
    // downgrade -- the one with the real bug this whole EFI64 path exists to route around) --
    // without this tag, GRUB exits boot services on its own first, and its own dispatch logic
    // takes the 32-bit path regardless of the EFI64 entry-address tag below being present at all.
    // `flags = 1` (optional): a loader that doesn't understand this tag should just ignore it, not
    // refuse to boot the image -- load-bearing for staying compatible with Limine's own
    // multiboot2 protocol implementation, which must keep working unaffected by this tag existing.
    ".short 7", // type
    ".short 1", // flags (optional)
    ".long 8",  // size (bare tag, no payload)
    // EFI64 entry-address tag (type 9, spec section 3.5's EFI amd64 "Machine state" -- see
    // `_efi64_start`'s own doc comment for why this exists at all). Ignored by any loader that
    // isn't itself running under UEFI (real GRUB under BIOS, Limine's own multiboot2 protocol)
    // -- purely additive, doesn't change behavior for either of those already-working paths.
    ".short 9", // type
    ".short 0", // flags (not optional)
    ".long 12", // size
    ".long _efi64_start",
    ".long 0", // pad to the next 8-byte boundary (12 -> 16)
    // Framebuffer request tag (type 5, spec section 3.1.7) -- without this, a loader's own
    // graphics setup is undefined (real GRUB/Limine-as-multiboot2 may leave text mode active or
    // not touch video state at all), which is exactly the real, live bug this tag fixes: a real
    // boot reached a working `hush` prompt (confirmed via the serial-mirrored console log) with a
    // genuinely black screen -- no framebuffer had ever been set up for `console::framebuffer` to
    // find. `width`/`height`/`depth` all `0` means "no preference, loader's choice" (spec's own
    // documented meaning for that field combination). `flags = 1` (optional): a loader that can't
    // satisfy this should still boot us, just without a framebuffer, matching this tag's sibling
    // `EFI_BS` tag's own precedent above rather than refusing to boot outright.
    ".short 5", // type
    ".short 1", // flags (optional)
    ".long 20", // size
    ".long 0",  // width (no preference)
    ".long 0",  // height (no preference)
    ".long 0",  // depth (no preference)
    ".long 0",  // pad to the next 8-byte boundary (20 -> 24)
    // End tag.
    ".long 0",
    ".long 8",
    "mb2_header_end:",
    // --- scratch data + temporary page tables (real BSS: zero-filled by any spec-compliant ELF
    // loader, so no explicit zeroing loop is needed here) ---
    ".section .boot32.bss, \"aw\", @nobits",
    ".align 16",
    "boot32_stack_bottom:",
    // 1 MiB -- real, measured need, not the smoke test's own original 64 KiB guess. This stack
    // never gets replaced by a "real" per-process kernel stack this early in boot (see this
    // static's own doc comment above) -- it's still the active call stack all the way through
    // `oxidebsd::init()` AND every module's own `module_init`, INCLUDING `sys/modules/oxfs`'s real
    // mount-or-format pass over its entire seeded content. Found live via a real, silent (no
    // guard page) stack overflow: the original 64 KiB was sized only for `smoke/
    // multiboot2-boot-smoke`'s own minimal `oxidebsd::init()`-then-exit workload, never revisited
    // once `regress/multiboot2-kernel` (the real kernel, module loading included) started using this
    // same trampoline -- a deep call chain parsing/relocating `sys/modules/oxfs`'s own ~241 MiB object
    // (thousands of ELF sections) overran it, corrupting adjacent memory including a live
    // `BootInfoFrameAllocator`'s own `free_list` field on the stack further up the same chain
    // (confirmed via `addr2line` against the exact faulting `RIP`/stack pointer, not guessed).
    // Comfortably inside the 64 MiB low-identity window (`temp_pd_low`) this lives within.
    ".skip 0x100000",
    ".global boot32_stack_top",
    "boot32_stack_top:",
    ".align 4096",
    ".global temp_pml4",
    "temp_pml4:",
    ".skip 4096",
    ".global temp_pdpt_low",
    "temp_pdpt_low:",
    ".skip 4096",
    ".global temp_pdpt_high",
    "temp_pdpt_high:",
    ".skip 4096",
    ".global temp_pd_low",
    "temp_pd_low:",
    ".skip 4096",
    ".global temp_pd_high",
    "temp_pd_high:",
    ".skip 4096",
    // --- GDT + saved handoff registers ---
    ".section .boot32.data, \"aw\"",
    ".align 8",
    "gdt32_start:",
    ".quad 0x0000000000000000", // null
    ".quad 0x00CF9A000000FFFF", // 0x08: 32-bit code, base 0, limit 4G, present, ring0
    ".quad 0x00CF92000000FFFF", // 0x10: 32-bit data, base 0, limit 4G, present, ring0
    ".quad 0x00AF9A000000FFFF", // 0x18: 64-bit code (L=1, D=0), present, ring0
    "gdt32_end:",
    "gdt32_ptr:",
    ".word gdt32_end - gdt32_start - 1",
    ".long gdt32_start",
    "mb2_saved_magic:",
    ".long 0",
    // A full quad, not a long -- the classic 32-bit entry's mbi pointer always fits in 32 bits
    // (real mode/EBX-limited), but the EFI64 entry's (see `_efi64_start`) could in principle need
    // the full 64 bits under a UEFI system's much larger physical address space. Both entry paths
    // write this same slot; `_start64_prelim` below reads it back as a full 64-bit value either
    // way.
    "mb2_saved_info_ptr:",
    ".quad 0",
    "far_ptr_flush:",
    ".long _start32_flush",
    ".word 0x08",
    "far_ptr_long_mode:",
    ".long _start64_prelim",
    ".word 0x18",
    // --- Stage A: 32-bit trampoline ---
    ".section .boot32.text, \"ax\"",
    ".code32",
    ".global _start32",
    "_start32:",
    "cli",
    // Multiboot2 spec section 5.2: EAX = magic, EBX = physical address of the info structure.
    "mov [mb2_saved_magic], eax",
    // EBX only ever holds a 32-bit address on this entry path; zero the high dword explicitly
    // rather than relying on the slot's own zero-initialized content (defensive, in case this
    // code path is ever reached a second time on a real machine).
    "mov [mb2_saved_info_ptr], ebx",
    "mov dword ptr [mb2_saved_info_ptr+4], 0",
    "mov esp, offset boot32_stack_top",
    // Never trust the loader's own GDT past this point (spec-undefined contents/selectors).
    "lgdt [gdt32_ptr]",
    "mov ax, 0x10",
    "mov ds, ax",
    "mov es, ax",
    "mov fs, ax",
    "mov gs, ax",
    "mov ss, ax",
    "jmp fword ptr [far_ptr_flush]",
    "_start32_flush:",
    // PD_LOW: identity-map physical [0, 64 MiB) -- see this file's module doc comment for why this
    // window's size is a fixed constant while PD_HIGH's below is not.
    "mov edi, offset temp_pd_low",
    "xor eax, eax",
    "mov ecx, 32",
    "1:",
    "mov edx, eax",
    "or edx, 0x83", // PRESENT | WRITABLE | HUGE_PAGE
    "mov [edi], edx",
    "mov dword ptr [edi+4], 0",
    "add eax, 0x200000",
    "add edi, 8",
    "loop 1b",
    // PD_HIGH: map the real kernel image's own physical range [_kernel_phys_start,
    // _kernel_phys_end), sized dynamically -- never a hardcoded page count.
    "mov eax, offset _kernel_phys_end",
    "add eax, 0x1FFFFF",
    "shr eax, 21",
    "mov esi, offset _kernel_phys_start",
    "shr esi, 21",
    "sub eax, esi",
    "mov ecx, eax",
    "mov edi, offset temp_pd_high",
    "mov eax, offset _kernel_phys_start",
    "2:",
    "mov edx, eax",
    "or edx, 0x83",
    "mov [edi], edx",
    "mov dword ptr [edi+4], 0",
    "add eax, 0x200000",
    "add edi, 8",
    "loop 2b",
    // PDPT_LOW[0] -> PD_LOW
    "mov eax, offset temp_pd_low",
    "or eax, 0x03", // PRESENT | WRITABLE
    "mov [temp_pdpt_low], eax",
    "mov dword ptr [temp_pdpt_low+4], 0",
    // PDPT_HIGH[510] -> PD_HIGH (0xffffffff80000000 is exactly PDPT index 510)
    "mov eax, offset temp_pd_high",
    "or eax, 0x03",
    "mov [temp_pdpt_high + 510*8], eax",
    "mov dword ptr [temp_pdpt_high + 510*8 + 4], 0",
    // PML4[0] -> PDPT_LOW, PML4[511] -> PDPT_HIGH
    "mov eax, offset temp_pdpt_low",
    "or eax, 0x03",
    "mov [temp_pml4], eax",
    "mov dword ptr [temp_pml4+4], 0",
    "mov eax, offset temp_pdpt_high",
    "or eax, 0x03",
    "mov [temp_pml4 + 511*8], eax",
    "mov dword ptr [temp_pml4 + 511*8 + 4], 0",
    "mov eax, offset temp_pml4",
    "mov cr3, eax",
    "mov eax, cr4",
    "or eax, 1 << 5", // PAE
    "mov cr4, eax",
    "mov ecx, 0xC0000080", // IA32_EFER
    "rdmsr",
    "or eax, 1 << 8", // LME
    "wrmsr",
    "mov eax, cr0",
    "or eax, 1 << 31", // PG
    "mov cr0, eax",
    "jmp fword ptr [far_ptr_long_mode]",
    // --- Stage A tail: land in 64-bit long mode, hand off to Rust ---
    ".code64",
    ".global _start64_prelim",
    "_start64_prelim:",
    "mov ax, 0x10",
    "mov ds, ax",
    "mov es, ax",
    "mov fs, ax",
    "mov gs, ax",
    "mov ss, ax",
    // Falls through into the shared tail below -- also reached directly by `_efi64_start`, which
    // skips this segment-register reload entirely (see that label's own doc comment for why).
    "mb2_enter_rust:",
    "mov rsp, offset boot32_stack_top",
    // System V AMD64 requires RSP % 16 == 0 *at the point of a CALL instruction*, i.e. RSP % 16
    // == 8 immediately upon entry to a normal callee (after CALL's own implicit return-address
    // push). Landing here via a plain `jmp` (see below) never does that implicit push, so a
    // 16-aligned boot32_stack_top leaves RSP at the *wrong* parity for every call this trampoline
    // "enters" Rust as if it were one -- harmless for most code, but a real #GP the first time
    // anything needs genuine 16-byte alignment (found live: this crashed silently inside
    // cpu::fpu::init()'s `fxsave`, which faults on a misaligned operand).
    "sub rsp, 8",
    // System V AMD64: first two integer args in RDI/RSI. A plain 32-bit `mov` zero-extends into
    // the full 64-bit register (correct for the classic entry's always-32-bit magic); the mbi
    // pointer is read back as a full 64-bit quad, since `_efi64_start` may have stored a value
    // needing more than 32 bits there.
    "mov eax, [mb2_saved_magic]",
    "mov edi, eax",
    "mov rsi, [mb2_saved_info_ptr]",
    // Indirect jump through a register, not a direct `jmp multiboot2_rust_entry` -- the
    // displacement between this low trampoline code and the higher-half Rust entry point is right
    // at the edge of (and, depending on exact kernel size, potentially beyond) a `jmp rel32`'s
    // range, since the higher-half base is itself -2 GiB. `mov reg, imm64` always encodes as a
    // full 64-bit immediate (movabs), so this has no such range limit.
    "mov rax, offset multiboot2_rust_entry",
    "jmp rax",
    // --- EFI64 entry point: real GRUB running under UEFI hits a genuine internal bug trying to
    // downgrade itself from 64-bit long mode back to 32-bit protected mode to satisfy the classic
    // entry's machine-state contract -- confirmed live via a fully isolated repro (a trivial,
    // unrelated hand-assembled kernel crashes identically through the exact same GRUB+OVMF+QEMU
    // pipeline; GRUB's own UEFI/config-parsing functionality is otherwise fine, narrowing this to
    // specifically the `multiboot2` command's own kernel-boot transition). The spec's answer to
    // exactly this is the EFI64 entry-address tag (type 9, in `.multiboot_header` above): it lets
    // an EFI-aware loader hand off directly in 64-bit mode, boot services still running, skipping
    // that transition entirely. Ignored by any loader that isn't itself running under UEFI.
    //
    // Already in 64-bit long mode with paging enabled (mandatory prerequisites for x86_64 UEFI
    // itself -- CR4.PAE/EFER.LME/CR0.PG are guaranteed already set, unlike the classic entry).
    // *Not* already safe to run ordinary Rust code, though: EFI's own page tables are whatever the
    // firmware set up for itself (typically a plain low-physical-range identity map), which has no
    // reason to cover this kernel's own linked higher-half VMA (0xffffffff80000000+) -- so this
    // still needs the exact same temporary-page-table bootstrap the classic entry's own
    // `_start32_flush` does, just skipping the parts made unnecessary by already being in long
    // mode (no GDT reload -- UEFI guarantees flat, sane segments, unlike the classic entry's
    // spec-undefined ones; no PAE/LME/CR0.PG enabling).
    //
    // Real spec uncertainty, resolved empirically rather than assumed: the exact EAX/RBX handoff
    // convention for this specific tag is far less battle-tested than the classic entry's (most
    // real Multiboot2 kernels never implement it at all). Implemented here as EAX=magic
    // (0x36d76289, matching the classic entry -- the value is a plain 32-bit constant either way)
    // and RBX=the real (possibly >32-bit, since a UEFI system's physical address space isn't
    // 32-bit-limited) mbi pointer -- if wrong, `init_from_mbi`'s own `assert_eq!` on the magic
    // will print the actual value it saw, which is the fastest way to find out.
    ".global _efi64_start",
    "_efi64_start:",
    "cli",
    "mov [mb2_saved_magic], eax",
    "mov [mb2_saved_info_ptr], rbx",
    // PD_LOW / PD_HIGH / PDPT_LOW / PDPT_HIGH / PML4 -- identical logic and identical target
    // memory to the classic entry's own `_start32_flush` (see that label's own comments for what
    // each step does), just re-encoded for `.code64` context throughout: the exact same
    // instructions assembled under `.code32` cannot simply be jumped into from real 64-bit-mode
    // execution, since the two modes decode some of the same byte patterns differently.
    "mov edi, offset temp_pd_low",
    "xor eax, eax",
    "mov ecx, 32",
    "3:",
    "mov edx, eax",
    "or edx, 0x83",
    "mov [edi], edx",
    "mov dword ptr [edi+4], 0",
    "add eax, 0x200000",
    "add edi, 8",
    "loop 3b",
    "mov eax, offset _kernel_phys_end",
    "add eax, 0x1FFFFF",
    "shr eax, 21",
    "mov esi, offset _kernel_phys_start",
    "shr esi, 21",
    "sub eax, esi",
    "mov ecx, eax",
    "mov edi, offset temp_pd_high",
    "mov eax, offset _kernel_phys_start",
    "4:",
    "mov edx, eax",
    "or edx, 0x83",
    "mov [edi], edx",
    "mov dword ptr [edi+4], 0",
    "add eax, 0x200000",
    "add edi, 8",
    "loop 4b",
    "mov eax, offset temp_pd_low",
    "or eax, 0x03",
    "mov [temp_pdpt_low], eax",
    "mov dword ptr [temp_pdpt_low+4], 0",
    "mov eax, offset temp_pd_high",
    "or eax, 0x03",
    "mov [temp_pdpt_high + 510*8], eax",
    "mov dword ptr [temp_pdpt_high + 510*8 + 4], 0",
    "mov eax, offset temp_pdpt_low",
    "or eax, 0x03",
    "mov [temp_pml4], eax",
    "mov dword ptr [temp_pml4+4], 0",
    "mov eax, offset temp_pdpt_high",
    "or eax, 0x03",
    "mov [temp_pml4 + 511*8], eax",
    "mov dword ptr [temp_pml4 + 511*8 + 4], 0",
    // Zero-extends into RAX (writing a 32-bit register in 64-bit mode always does), but the
    // control-register move itself needs the 64-bit register name -- `mov cr3, eax` isn't valid
    // encoding in long mode the way it is in the classic entry's still-32-bit context.
    "mov eax, offset temp_pml4",
    "mov cr3, rax",
    "jmp mb2_enter_rust",
    ".popsection",
);

/// Stage B: validates the Multiboot2 handoff, parses the memory map, builds and installs the real
/// final page tables, and returns a `&'static BootInfo` -- the exact point where this boot path
/// converges with `boot::read_boot_info()`'s own return value. Called by the
/// `multiboot2_entry_point!`-generated `multiboot2_rust_entry`, never directly.
///
/// # Safety
///
/// Must be called at most once, from `_start64_prelim` (or an equivalent caller that has already
/// installed Stage A's own temporary page tables) -- reads raw physical memory at `mbi_phys`
/// through the temporary identity mapping, and installs a brand new `CR3`.
pub unsafe fn init_from_mbi(magic: u32, mbi_phys: u64) -> &'static BootInfo {
    assert_eq!(
        magic, MULTIBOOT2_BOOTLOADER_MAGIC,
        "invalid Multiboot2 magic in EAX: {magic:#x} (expected {MULTIBOOT2_BOOTLOADER_MAGIC:#x})"
    );

    // Parse tags before touching CR3 again -- simplest to reach `mbi_phys` (a low physical
    // address) via Stage A's own still-active temporary tables rather than depend on ordering
    // relative to `install_final_page_tables` (whose own final tables happen to keep the same low
    // window mapped too -- see `temp_pdpt_low`'s own doc comment for why that turned out to be
    // required, not just convenient).
    let entries = unsafe { parse_mmap(mbi_phys) };

    unsafe { install_final_page_tables() };

    // See `boot::set_hhdm_offset`'s own doc comment: without this, `boot::hhdm_offset()` panics
    // the instant anything calls it under this boot path (e.g. doom's own `/dev/fb0` mmap).
    super::set_hhdm_offset(MULTIBOOT2_HHDM_OFFSET);

    static mut BOOT_INFO: Option<BootInfo> = None;
    unsafe {
        BOOT_INFO = Some(BootInfo {
            physical_memory_offset: MULTIBOOT2_HHDM_OFFSET,
            memory_map: entries,
        });
        (&raw const BOOT_INFO).as_ref().unwrap().as_ref().unwrap()
    }
}

/// Real ceiling on how many Multiboot2 memory-map entries this boot path can carry into
/// `BootInfo` -- generous for any real or QEMU x86_64 machine's own memory map (typically well
/// under 20 entries), documented rather than silently truncated without comment, matching this
/// file's `MULTIBOOT2_HHDM_CEILING_BYTES` precedent.
const MAX_MMAP_ENTRIES: usize = 64;

static mut MMAP_STORAGE: [Entry; MAX_MMAP_ENTRIES] = [const {
    Entry {
        base: 0,
        length: 0,
        type_: 0,
    }
}; MAX_MMAP_ENTRIES];
static mut MMAP_PTRS: [MaybeUninit<&'static Entry>; MAX_MMAP_ENTRIES] =
    [const { MaybeUninit::uninit() }; MAX_MMAP_ENTRIES];

/// Populated by `parse_mmap` below if the loader's own Multiboot2 info structure carries a real
/// RGB framebuffer info tag (spec section 3.6.9) -- see `boot::FbInfo`'s own doc comment for why
/// this exists at all (Limine's own framebuffer request/response mechanism is unreachable under
/// this boot path). `None` if no such tag is present (e.g. a loader that ignored this file's own
/// framebuffer *request* header tag) or reports a non-RGB type this driver doesn't handle.
static mut MB2_FB_INFO: Option<super::FbInfo> = None;

pub fn primary_framebuffer() -> Option<super::FbInfo> {
    // SAFETY: written at most once, by `parse_mmap`, before any other code (including this
    // function's own first real caller, `console::framebuffer::init`) runs.
    unsafe { *core::ptr::addr_of!(MB2_FB_INFO) }
}

/// Walks the Multiboot2 info structure at `mbi_phys` (spec section 3.4: a `total_size`/`reserved`
/// header followed by a sequence of 8-byte-aligned tags), keeping only the `MULTIBOOT_TAG_TYPE_MMAP`
/// tag's entries, translated into the exact `limine::memmap::Entry` shape
/// `memory::BootInfoFrameAllocator` already consumes unmodified.
///
/// # Safety
///
/// `mbi_phys` must be a physical address currently reachable through an active identity mapping
/// (true immediately after Stage A, via `temp_pd_low`), and this must not be called concurrently
/// with another call (writes shared `static mut` storage).
unsafe fn parse_mmap(mbi_phys: u64) -> &'static [&'static Entry] {
    let base = mbi_phys as usize;
    // SAFETY: per this function's own contract, `base` is identity-mapped right now.
    let total_size = unsafe { (base as *const u32).read_unaligned() } as usize;

    let mut offset = 8usize; // skip the { total_size, reserved } header
    let mut count = 0usize;
    while offset + 8 <= total_size {
        let tag_addr = base + offset;
        // SAFETY: tag_addr is within [base, base + total_size), which the Multiboot2 spec
        // guarantees the loader made available starting at mbi_phys.
        let typ = unsafe { (tag_addr as *const u32).read_unaligned() };
        let size = unsafe { ((tag_addr + 4) as *const u32).read_unaligned() } as usize;
        if typ == TAG_TYPE_END {
            break;
        }
        if typ == TAG_TYPE_MMAP && size >= 16 {
            let entry_size = unsafe { ((tag_addr + 8) as *const u32).read_unaligned() } as usize;
            if entry_size > 0 {
                let entries_base = tag_addr + 16;
                let entry_count = (size - 16) / entry_size;
                for i in 0..entry_count {
                    if count >= MAX_MMAP_ENTRIES {
                        break;
                    }
                    let entry_addr = entries_base + i * entry_size;
                    // SAFETY: entry_addr is within this same tag's own [tag_addr, tag_addr+size).
                    let mb_base = unsafe { (entry_addr as *const u64).read_unaligned() };
                    let mb_length = unsafe { ((entry_addr + 8) as *const u64).read_unaligned() };
                    let mb_type = unsafe { ((entry_addr + 16) as *const u32).read_unaligned() };
                    // SAFETY: count < MAX_MMAP_ENTRIES, checked above; no other code touches
                    // MMAP_STORAGE concurrently (see this function's own safety contract).
                    unsafe {
                        (&raw mut MMAP_STORAGE)
                            .cast::<Entry>()
                            .add(count)
                            .write(Entry {
                                base: mb_base,
                                length: mb_length,
                                type_: translate_mmap_type(mb_type),
                            });
                    }
                    count += 1;
                }
            }
        }
        // Real Multiboot2 framebuffer info tag (spec section 3.6.9) -- see `MB2_FB_INFO`'s own
        // doc comment. `size >= 32` covers the tag's fixed-size fields (type/size/addr/pitch/
        // width/height/bpp/type/reserved); the extra `>= 38` guard below covers the 6 further
        // bytes real RGB color-info carries (red/green/blue field-position + mask-size pairs).
        // **`reserved` is a `u16`, not a `u8`** -- confirmed live, the hard way: an earlier
        // version of this code treated it as one byte, reading every color-info field exactly one
        // byte too early. The resulting garbage (`red(shift=0,size=16) green(shift=8,size=8)
        // blue(shift=8,size=0)`) rendered `console::framebuffer`'s text console in the wrong
        // color (blue instead of white/grey) while doom's own direct pixel writes -- a completely
        // separate path, bypassing this tag's color info entirely -- stayed correct throughout,
        // which is what made this easy to misdiagnose as a doom-specific issue at first glance.
        if typ == TAG_TYPE_FRAMEBUFFER && size >= 32 {
            let fb_addr = unsafe { ((tag_addr + 8) as *const u64).read_unaligned() };
            let fb_pitch = unsafe { ((tag_addr + 16) as *const u32).read_unaligned() };
            let fb_width = unsafe { ((tag_addr + 20) as *const u32).read_unaligned() };
            let fb_height = unsafe { ((tag_addr + 24) as *const u32).read_unaligned() };
            let fb_bpp = unsafe { ((tag_addr + 28) as *const u8).read_unaligned() };
            let fb_type = unsafe { ((tag_addr + 29) as *const u8).read_unaligned() };
            if fb_type == FRAMEBUFFER_TYPE_RGB && size >= 38 {
                let red_shift = unsafe { ((tag_addr + 32) as *const u8).read_unaligned() };
                let red_size = unsafe { ((tag_addr + 33) as *const u8).read_unaligned() };
                let green_shift = unsafe { ((tag_addr + 34) as *const u8).read_unaligned() };
                let green_size = unsafe { ((tag_addr + 35) as *const u8).read_unaligned() };
                let blue_shift = unsafe { ((tag_addr + 36) as *const u8).read_unaligned() };
                let blue_size = unsafe { ((tag_addr + 37) as *const u8).read_unaligned() };
                // SAFETY: written at most once, before any other code reads `MB2_FB_INFO` (see
                // that static's own doc comment).
                unsafe {
                    MB2_FB_INFO = Some(super::FbInfo {
                        // `fb_addr` is a raw *physical* address (spec section 3.6.9) -- unlike
                        // Limine's own `Framebuffer::address()`, which is already a directly
                        // dereferenceable virtual pointer. Translated via this boot path's own
                        // HHDM window (`install_final_page_tables` maps every 2 MiB chunk up to
                        // `MULTIBOOT2_HHDM_CEILING_BYTES` unconditionally, MMIO included, not just
                        // memory-map-reported "usable" RAM -- a real framebuffer's PCI-BAR-mapped
                        // physical address is comfortably within that range on any real or QEMU
                        // x86_64 target this project builds for).
                        address: fb_addr + MULTIBOOT2_HHDM_OFFSET,
                        width: fb_width as u64,
                        height: fb_height as u64,
                        pitch: fb_pitch as u64,
                        bpp: fb_bpp as u16,
                        red_mask_size: red_size,
                        red_mask_shift: red_shift,
                        green_mask_size: green_size,
                        green_mask_shift: green_shift,
                        blue_mask_size: blue_size,
                        blue_mask_shift: blue_shift,
                    });
                }
            }
        }
        // Every tag is padded to an 8-byte boundary (spec section 3.4).
        offset += (size + 7) & !7;
    }

    // SAFETY: entries [0, count) were just written above by this same function, no aliasing
    // reference exists yet -- safe to take a mutable slice before handing out any `&'static Entry`.
    count = unsafe {
        let storage: &mut [Entry] =
            core::slice::from_raw_parts_mut((&raw mut MMAP_STORAGE).cast::<Entry>(), count);
        exclude_kernel_range(storage, count)
    };

    // SAFETY: entries [0, count) were just written above; no aliasing &mut exists.
    unsafe {
        for i in 0..count {
            let entry_ref: &'static Entry = &*(&raw const MMAP_STORAGE).cast::<Entry>().add(i);
            MMAP_PTRS[i].write(entry_ref);
        }
        core::slice::from_raw_parts((&raw const MMAP_PTRS).cast::<&'static Entry>(), count)
    }
}

/// Carves the kernel's own real physical footprint (`[BOOT32_TRAMPOLINE_PHYS_BASE,
/// _kernel_phys_end)`, covering both the Stage A trampoline and the main kernel image) out of any
/// `MEMMAP_USABLE` entry that overlaps it, clipping or splitting that entry as needed. Returns the
/// (possibly larger, if an entry was split in two) entry count.
///
/// **Why this is required at all, unlike the Limine boot path**: a real Multiboot2 memory map
/// (spec section 3.6.8) reports raw firmware-level regions (from the BIOS e820 map or UEFI's own
/// memory map) with no concept of "where the loader put the kernel" -- unlike Limine's own memory
/// map, which already reports the kernel/modules region as a distinct, non-`MEMMAP_USABLE` type.
/// Left unfixed, `memory::BootInfoFrameAllocator`'s bump allocator -- fed this raw map directly --
/// starts handing out frames from the low end of the first usable region, which for this boot path
/// begins at/near `BOOT32_TRAMPOLINE_PHYS_BASE`: for any kernel image large enough that its own
/// footprint reaches into that region's *first* handful of frames (true for this kernel's real
/// build, whose embedded BusyBox/musl/Clang+LLVM/POSIX-corpus content puts the image well
/// into the hundreds of MiB -- see this file's own module doc comment), the very first heap/module
/// page allocated after boot silently aliases live kernel code/data/page-tables instead of real
/// free memory. Found live: a real, reproducible hang immediately after "mapping heap" logged, with
/// no panic (consistent with silent corruption of currently-executing code/page-table frames, not
/// a caught fault) -- confirmed absent once this exclusion pass was added. The (much smaller)
/// `multiboot2-boot-smoke` test's own tiny image just never had the misfortune of an early
/// allocation landing somewhere load-bearing.
fn exclude_kernel_range(entries: &mut [Entry], count: usize) -> usize {
    let excl_start = BOOT32_TRAMPOLINE_PHYS_BASE;
    // Rounded UP to the next page boundary -- `_kernel_phys_end` (the linker-computed end of
    // `.bss`) is *not* page-aligned in general (nothing forces the last byte of `.bss` onto a
    // 4096 boundary), but `BootInfoFrameAllocator::allocate_frame`'s own `region.base / 4096`
    // truncates *down* when computing a region's first frame number. Left un-rounded here, the
    // very first frame handed out from the region this shrinks still starts at
    // `floor(_kernel_phys_end / 4096) * 4096` -- *inside* the excluded kernel range by however many
    // bytes `_kernel_phys_end` overshoots its own page boundary. Found live: that overlap frame is
    // exactly where `MMAP_STORAGE`/`MMAP_PTRS` (this same file's own memory-map entries) happen to
    // sit, right at the tail end of the kernel's `.bss` -- the first consumer to receive that frame
    // (confirmed via `addr2line` against a real fault) zeroed/overwrote them, corrupting a `&'static
    // Entry` pointer this exact function's own caller chain reads back later, producing a page
    // fault dereferencing the resulting garbage address.
    let excl_end = ((&raw const _kernel_phys_end) as u64).div_ceil(4096) * 4096;

    let mut new_count = count;
    // Snapshot the pre-exclusion count: a split below can append one new entry past the original
    // range, which never itself overlaps `[excl_start, excl_end)` (it starts at `excl_end`), so
    // re-scanning it would be wasted work, not a correctness issue either way.
    for i in 0..count {
        if entries[i].type_ != MEMMAP_USABLE {
            continue;
        }
        let entry_base = entries[i].base;
        let entry_end = entry_base + entries[i].length;
        let overlap_start = entry_base.max(excl_start);
        let overlap_end = entry_end.min(excl_end);
        if overlap_start >= overlap_end {
            continue; // no real overlap
        }

        let head_len = overlap_start - entry_base;
        let tail_len = entry_end - overlap_end;
        if head_len == 0 && tail_len == 0 {
            // The exclusion fully covers this entry -- drop it entirely.
            entries[i].type_ = MEMMAP_RESERVED;
        } else if tail_len == 0 {
            // Exclusion eats the tail only -- shrink in place.
            entries[i].length = head_len;
        } else if head_len == 0 {
            // Exclusion eats the head only -- shift the start forward in place.
            entries[i].base = overlap_end;
            entries[i].length = tail_len;
        } else {
            // Exclusion is strictly inside this entry -- shrink to the head in place, and append a
            // new entry for the tail (dropped silently if `MAX_MMAP_ENTRIES` is already exhausted;
            // real machines report well under 20 raw entries, so this is not expected to fire).
            entries[i].length = head_len;
            if new_count < entries.len() {
                entries[new_count] = Entry {
                    base: overlap_end,
                    length: tail_len,
                    type_: MEMMAP_USABLE,
                };
                new_count += 1;
            }
        }
    }
    new_count
}

fn translate_mmap_type(mb_type: u32) -> u64 {
    match mb_type {
        MULTIBOOT_MEMORY_AVAILABLE => MEMMAP_USABLE,
        MULTIBOOT_MEMORY_ACPI_RECLAIMABLE => MEMMAP_ACPI_RECLAIMABLE,
        MULTIBOOT_MEMORY_NVS => MEMMAP_ACPI_NVS,
        MULTIBOOT_MEMORY_BADRAM => MEMMAP_BAD_MEMORY,
        // MULTIBOOT_MEMORY_RESERVED (2) and anything this spec version doesn't define yet both
        // land here -- MEMMAP_RESERVED is the safe default (never treated as usable).
        _ => MEMMAP_RESERVED,
    }
}

static mut FINAL_PML4: PageTable = PageTable::new();
static mut HHDM_PDPT: PageTable = PageTable::new();
static mut HHDM_PDS: [PageTable; HHDM_PD_COUNT] = [const { PageTable::new() }; HHDM_PD_COUNT];

/// `MULTIBOOT2_HHDM_OFFSET`'s own PML4 index (256 -- see this constant's own value: exactly
/// `256 * 512 GiB`).
const HHDM_PML4_INDEX: usize = 256;
/// `KERNEL_HIGHER_HALF_BASE`'s own PML4 index (511 -- the same "topmost 2 GiB" slot the
/// plain-Limine kernel script's own comment names).
const KERNEL_PML4_INDEX: usize = 511;
/// Stage A's own low-identity window's PML4 index (0) -- see `temp_pdpt_low`'s own doc comment
/// above for why the final tables must keep this mapped too, not just the temporary ones.
const LOW_IDENTITY_PML4_INDEX: usize = 0;

/// Builds the real, final page tables: a fresh `MULTIBOOT2_HHDM_OFFSET`-based window covering
/// `MULTIBOOT2_HHDM_CEILING_BYTES` of physical memory (this boot path's own HHDM), plus the exact
/// same kernel-higher-half *and* low-identity mappings Stage A's temporary tables already built
/// (both reused directly, not rebuilt -- their content never changes). The low-identity window is
/// *not* optional to keep, even though the fresh HHDM window below also covers all of physical
/// memory, low addresses included -- see `temp_pdpt_low`'s own doc comment for why (the
/// currently-running stack lives there).
///
/// # Safety
///
/// Must run with Stage A's own temporary tables still active (this function's own writes to
/// `FINAL_PML4`/`HHDM_PDPT`/`HHDM_PDS` rely on the temporary kernel-higher-half alias still
/// mapping this crate's own `.bss`), and must be called at most once.
unsafe fn install_final_page_tables() {
    let kernel_phys_start = (&raw const _kernel_phys_start) as u64;
    let kernel_phys_end = (&raw const _kernel_phys_end) as u64;
    assert!(
        (kernel_phys_end - kernel_phys_start).div_ceil(HUGE_PAGE_SIZE) <= 512,
        "kernel image ({} bytes) exceeds the single-PD-table (1 GiB) ceiling this boot path's \
         temporary/final page tables assume",
        kernel_phys_end - kernel_phys_start
    );

    // SAFETY: per this function's own contract, these statics are reachable right now through
    // Stage A's still-active temporary kernel-higher-half alias.
    let hhdm_pds = unsafe { &mut *(&raw mut HHDM_PDS) };
    for (pd_index, pd) in hhdm_pds.iter_mut().enumerate() {
        for (entry_index, entry) in pd.iter_mut().enumerate() {
            let phys = (pd_index as u64) * ONE_GIB + (entry_index as u64) * HUGE_PAGE_SIZE;
            entry.set_addr(
                PhysAddr::new(phys),
                PageTableFlags::PRESENT | PageTableFlags::WRITABLE | PageTableFlags::HUGE_PAGE,
            );
        }
    }

    let hhdm_pdpt = unsafe { &mut *(&raw mut HHDM_PDPT) };
    for (i, pd) in hhdm_pds.iter().enumerate() {
        let pd_phys = kernel_virt_to_phys(pd as *const PageTable as u64);
        hhdm_pdpt[i].set_addr(
            PhysAddr::new(pd_phys),
            PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
        );
    }

    let final_pml4 = unsafe { &mut *(&raw mut FINAL_PML4) };
    let hhdm_pdpt_phys = kernel_virt_to_phys(hhdm_pdpt as *const PageTable as u64);
    final_pml4[HHDM_PML4_INDEX].set_addr(
        PhysAddr::new(hhdm_pdpt_phys),
        PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
    );
    // `temp_pdpt_high` lives in `.boot32.data`, which -- unlike this crate's own ordinary
    // `.bss` -- has VMA == LMA (see x86_64-oxidebsd-multiboot2.ld), so its own address already
    // *is* its physical address; no kernel_virt_to_phys translation for this one.
    let temp_pdpt_high_phys = (&raw const temp_pdpt_high) as u64;
    final_pml4[KERNEL_PML4_INDEX].set_addr(
        PhysAddr::new(temp_pdpt_high_phys),
        PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
    );
    // See temp_pdpt_low's own doc comment above: the low-identity window has to survive into the
    // final tables too, since the currently-running stack lives inside it.
    let temp_pdpt_low_phys = (&raw const temp_pdpt_low) as u64;
    final_pml4[LOW_IDENTITY_PML4_INDEX].set_addr(
        PhysAddr::new(temp_pdpt_low_phys),
        PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
    );

    let final_pml4_phys = kernel_virt_to_phys(final_pml4 as *const PageTable as u64);
    let (_, flags) = Cr3::read();
    unsafe {
        Cr3::write(
            PhysFrame::containing_address(PhysAddr::new(final_pml4_phys)),
            flags,
        );
    }
}

/// Drop-in Multiboot2 counterpart to `limine_entry_point!` -- same two-line-per-call-site shape,
/// same `fn(&'static BootInfo) -> !` calling convention for `$path`, so a `tests/*.rs` file's own
/// `main` needs no changes to run under either boot path.
#[macro_export]
macro_rules! multiboot2_entry_point {
    ($path:path) => {
        #[unsafe(no_mangle)]
        extern "C" fn multiboot2_rust_entry(magic: u32, mbi_phys: u64) -> ! {
            let boot_info: &'static $crate::boot::BootInfo =
                unsafe { $crate::boot::multiboot2::init_from_mbi(magic, mbi_phys) };
            let f: fn(&'static $crate::boot::BootInfo) -> ! = $path;
            f(boot_info)
        }
    };
}
