//! Multiboot2 boot path: the Multiboot2 header, a real 32-bit-protected-mode-to-64-bit-long-mode
//! bootstrap trampoline, Multiboot2 info-tag parsing, and the final page tables -- everything
//! needed to reach the exact same `oxidebsd::init(&BootInfo)` entry point the Limine boot path
//! reaches, from a completely different (and much more primitive) starting CPU state. See
//! CLAUDE.md's Multiboot2 section for the full design/staging.
//!
//! **Why this needs its own from-scratch trampoline, not a header tweak**: regardless of loader --
//! real GRUB, or Limine's own vendored `protocol: multiboot2` support -- the CPU handoff for a
//! Multiboot2 kernel lands in 32-bit protected mode, paging disabled, a minimal/undefined GDT (see
//! the Multiboot2 spec's "Machine state" section) -- nothing like the 64-bit long mode with paging
//! and an HHDM already active that `limine_entry_point!`'s `kmain` gets to assume.
//!
//! **Two-stage trampoline**, matching this codebase's existing convention of a tiny hand-rolled
//! asm stub handing off to ordinary Rust as soon as possible (see `src/process/fault_trampoline.rs`
//! /`context_switch.rs`'s own `global_asm!` blocks for precedent):
//! - Stage A (`global_asm!`, below): `_start32` -- reads the real Multiboot2 handoff registers
//!   (`EAX`=magic, `EBX`=info-structure physical address), sets up a small stack, loads a minimal
//!   flat 32-bit GDT (the loader's own GDT contents are spec-undefined past entry), builds
//!   temporary page tables, enables PAE/`EFER.LME`/`CR0.PG`, and far-jumps into 64-bit mode at
//!   `_start64_prelim`, which reloads segment registers and jumps into ordinary Rust
//!   (`multiboot2_rust_entry`, generated by the `multiboot2_entry_point!` macro below).
//! - Stage B (ordinary Rust, `init_from_mbi`): validates the magic, parses the Multiboot2 memory
//!   map into the exact same `limine::memmap::Entry` shape `boot::BootInfo`/
//!   `memory::BootInfoFrameAllocator` already consume, builds a real *final* set of page tables
//!   (reusing Stage A's own kernel-image mapping, plus a fresh HHDM-style window), installs them
//!   via `Cr3::write`, and returns a `&'static BootInfo` -- from here on, completely
//!   indistinguishable from the Limine boot path.
//!
//! **Temporary vs. final page tables, and why the "low identity" and "kernel higher-half"
//! windows are sized completely differently**: the *low* identity window (`temp_pd_low`) only
//! needs to cover early low-memory boot structures (the trampoline's own code, and wherever
//! GRUB/Limine placed the Multiboot2 info structure -- always well under a few MiB in practice),
//! so a fixed, generous 64 MiB constant is fine and never goes stale. The *kernel higher-half*
//! window (`temp_pd_high`, reused directly by the final tables -- see `install_final_page_tables`)
//! has to cover the kernel's own **entire loaded image**, which is a completely different scale:
//! this kernel's own embedded BusyBox/musl/TinyCC/Clang+LLVM/POSIX-conformance-corpus content
//! makes `.rodata` alone upward of 100 MiB already (confirmed via `readelf -l` against a real
//! release build) and grows over time -- the exact "embedded corpus outgrew a fixed constant"
//! class of bug CLAUDE.md documents hitting the userland-load-base floor repeatedly. That window
//! is therefore sized dynamically, at boot, from the linker-provided `_kernel_phys_start`/
//! `_kernel_phys_end` symbols (see `x86_64-oxidebsd-multiboot2.ld`), never a hardcoded page count.

use core::arch::global_asm;
use core::mem::MaybeUninit;

use limine::memmap::{
    Entry, MEMMAP_ACPI_NVS, MEMMAP_ACPI_RECLAIMABLE, MEMMAP_BAD_MEMORY, MEMMAP_RESERVED,
    MEMMAP_USABLE,
};
use x86_64::PhysAddr;
use x86_64::registers::control::Cr3;
use x86_64::structures::paging::{PageTable, PageTableFlags, PhysFrame};

use super::BootInfo;

/// Multiboot2 spec magic values (Multiboot2 spec section 3 "OS image format" / section 5.2 "Machine
/// state").
const MULTIBOOT2_HEADER_MAGIC: u32 = 0xe852_50d6;
const MULTIBOOT2_BOOTLOADER_MAGIC: u32 = 0x36d7_6289;
const MULTIBOOT2_ARCH_I386: u32 = 0;

const TAG_TYPE_END: u32 = 0;
const TAG_TYPE_MMAP: u32 = 6;

/// Multiboot2 memory-map entry `type` field values (spec section 3.6.8).
const MULTIBOOT_MEMORY_AVAILABLE: u32 = 1;
const MULTIBOOT_MEMORY_ACPI_RECLAIMABLE: u32 = 3;
const MULTIBOOT_MEMORY_NVS: u32 = 4;
const MULTIBOOT_MEMORY_BADRAM: u32 = 5;
// MULTIBOOT_MEMORY_RESERVED (2) and any value this spec hasn't defined yet both fall through to
// the same MEMMAP_RESERVED translation below -- see `translate_mmap_type`.

const HUGE_PAGE_SIZE: u64 = 0x20_0000; // 2 MiB
const ONE_GIB: u64 = 0x4000_0000;

/// Same fixed higher-half base the plain-Limine kernel linker script already uses -- see
/// `x86_64-oxidebsd-multiboot2.ld`'s own doc comment for why `.text`/etc. keep this exact VMA.
const KERNEL_HIGHER_HALF_BASE: u64 = 0xffff_ffff_8000_0000;

/// A fixed HHDM-style offset for the Multiboot2 boot path, distinct from whatever value Limine
/// happens to pick for its own HHDM -- this path builds its own final page tables from scratch, so
/// nothing requires matching Limine's exact offset, only that `boot::BootInfo::
/// physical_memory_offset` and the mapping installed by `install_final_page_tables` agree.
pub const MULTIBOOT2_HHDM_OFFSET: u64 = 0xffff_8000_0000_0000;

/// Real ceiling for the HHDM window this boot path installs, matching `scripts/qemu_runner.sh`'s
/// `-m 8192`. A documented, deliberate scope limit versus Limine's full-range HHDM (which sizes
/// itself off the bootloader's own memory-map response) -- nothing at this point in boot has
/// parsed the real memory map yet (building that map is literally what this code is doing), so a
/// fixed ceiling is used instead, same simplification the real ceiling on the mmap-entry array
/// below already makes.
const MULTIBOOT2_HHDM_CEILING_BYTES: u64 = 8 * 1024 * 1024 * 1024;
const HHDM_PD_COUNT: usize = (MULTIBOOT2_HHDM_CEILING_BYTES / ONE_GIB) as usize;

unsafe extern "C" {
    /// Provided by `x86_64-oxidebsd-multiboot2.ld`: the physical load address of the main kernel
    /// image (`.text` onward -- *not* including the tiny `boot32` trampoline before it) and one
    /// past its end. Only ever used for their *addresses* (via `&raw const`), never dereferenced --
    /// the classic "linker symbol as an opaque address marker" idiom.
    static _kernel_phys_start: u8;
    static _kernel_phys_end: u8;
    /// Defined in the `global_asm!` block below: the physical addresses of the temporary kernel
    /// higher-half and low-identity PDPTs Stage A already built. Both are reused as-is by
    /// `install_final_page_tables` -- their content doesn't change between the temporary and final
    /// address spaces. The low-identity window in particular is *not* optional to carry over: the
    /// currently-executing call stack (`boot32_stack`, still in active use all the way from Stage
    /// A through `oxidebsd::init` and beyond -- nothing switches to a "real" kernel stack this
    /// early) lives inside it, so dropping it out from under the very stack the CPU is running on
    /// faults on the first instruction (typically a `ret`) that touches the stack after `CR3` is
    /// reloaded. Found live: everything up through the `Cr3::write` call itself succeeded, but
    /// execution never returned from `install_final_page_tables` -- a real, silent triple fault
    /// (no IDT exists yet at this point in boot), not a Rust panic.
    static temp_pdpt_high: u8;
    static temp_pdpt_low: u8;
}

/// Converts a virtual address inside the kernel's own higher-half image (`.text`/`.rodata`/
/// `.data`/`.bss` -- anything compiled as part of this crate, `#[link_section]`-tagged
/// `.boot32.*` statics excluded) to the physical address backing it, using the constant
/// relationship `x86_64-oxidebsd-multiboot2.ld`'s `AT()` placement guarantees: every one of those
/// sections has VMA `KERNEL_HIGHER_HALF_BASE + k` and LMA `_kernel_phys_start + k`, for the same
/// `k`, regardless of section.
fn kernel_virt_to_phys(virt: u64) -> u64 {
    let kernel_phys_start = (&raw const _kernel_phys_start) as u64;
    virt - KERNEL_HIGHER_HALF_BASE + kernel_phys_start
}

/// The Multiboot2 header itself (spec section 3) -- a bare "OS image format" header with a single
/// end tag, relying on GRUB's/Limine's own real ELF loader (program headers + `e_entry`) to
/// actually load the kernel, rather than any of the optional tags requesting the loader do more.
/// Must land within the file's first 32 KiB and be 8-byte aligned -- guaranteed here by
/// `x86_64-oxidebsd-multiboot2.ld` placing `.multiboot_header` first, right after `. = 0x100000`.
#[repr(C, align(8))]
struct Multiboot2Header {
    magic: u32,
    architecture: u32,
    header_length: u32,
    checksum: u32,
    end_tag_type: u32,
    end_tag_size: u32,
}

const MULTIBOOT2_HEADER_LEN: u32 = core::mem::size_of::<Multiboot2Header>() as u32;

#[used]
#[unsafe(link_section = ".multiboot_header")]
static MULTIBOOT2_HEADER: Multiboot2Header = Multiboot2Header {
    magic: MULTIBOOT2_HEADER_MAGIC,
    architecture: MULTIBOOT2_ARCH_I386,
    header_length: MULTIBOOT2_HEADER_LEN,
    // Real Multiboot2 checksum rule: magic + architecture + header_length + checksum == 0 (mod
    // 2^32).
    checksum: 0u32
        .wrapping_sub(MULTIBOOT2_HEADER_MAGIC)
        .wrapping_sub(MULTIBOOT2_ARCH_I386)
        .wrapping_sub(MULTIBOOT2_HEADER_LEN),
    end_tag_type: TAG_TYPE_END,
    end_tag_size: 8,
};

// Stage A: the 32-bit-protected-mode entry point and its far jump into 64-bit long mode. Intel
// syntax throughout, matching every other `global_asm!` block in this codebase.
//
// Register conservation note: `EAX`/`EBX` (the real Multiboot2 handoff registers) are stashed to
// memory immediately, before anything else touches them -- the temporary-page-table-building code
// below needs `EAX`/`EBX`/`ECX`/`EDX`/`ESI`/`EDI` freely as scratch.
//
// Far jumps use an indirect `jmp far ptr [mem]` through a small 6-byte offset:selector structure
// rather than a direct `jmp sel:label` immediate -- LLVM's integrated assembler (Intel dialect)
// rejects the latter's `sel:label` operand syntax outright ("unexpected token in argument list").
global_asm!(
    // --- scratch data + temporary page tables (real BSS: zero-filled by any spec-compliant ELF
    // loader, so no explicit zeroing loop is needed here) ---
    ".section .boot32.bss, \"aw\", @nobits",
    ".align 16",
    "boot32_stack_bottom:",
    ".skip 65536", // 64 KiB -- generous headroom for oxidebsd::init() + a smoke test's own main()
    ".global boot32_stack_top",
    "boot32_stack_top:",
    ".align 4096",
    ".global temp_pml4",
    "temp_pml4:",
    ".skip 4096",
    ".global temp_pdpt_low",
    "temp_pdpt_low:",
    ".skip 4096",
    ".global temp_pdpt_high",
    "temp_pdpt_high:",
    ".skip 4096",
    ".global temp_pd_low",
    "temp_pd_low:",
    ".skip 4096",
    ".global temp_pd_high",
    "temp_pd_high:",
    ".skip 4096",
    // --- GDT + saved handoff registers ---
    ".section .boot32.data, \"aw\"",
    ".align 8",
    "gdt32_start:",
    ".quad 0x0000000000000000", // null
    ".quad 0x00CF9A000000FFFF", // 0x08: 32-bit code, base 0, limit 4G, present, ring0
    ".quad 0x00CF92000000FFFF", // 0x10: 32-bit data, base 0, limit 4G, present, ring0
    ".quad 0x00AF9A000000FFFF", // 0x18: 64-bit code (L=1, D=0), present, ring0
    "gdt32_end:",
    "gdt32_ptr:",
    ".word gdt32_end - gdt32_start - 1",
    ".long gdt32_start",
    "mb2_saved_magic:",
    ".long 0",
    "mb2_saved_info_ptr:",
    ".long 0",
    "far_ptr_flush:",
    ".long _start32_flush",
    ".word 0x08",
    "far_ptr_long_mode:",
    ".long _start64_prelim",
    ".word 0x18",
    // --- Stage A: 32-bit trampoline ---
    ".section .boot32.text, \"ax\"",
    ".code32",
    ".global _start32",
    "_start32:",
    "cli",
    // Multiboot2 spec section 5.2: EAX = magic, EBX = physical address of the info structure.
    "mov [mb2_saved_magic], eax",
    "mov [mb2_saved_info_ptr], ebx",
    "mov esp, offset boot32_stack_top",
    // Never trust the loader's own GDT past this point (spec-undefined contents/selectors).
    "lgdt [gdt32_ptr]",
    "mov ax, 0x10",
    "mov ds, ax",
    "mov es, ax",
    "mov fs, ax",
    "mov gs, ax",
    "mov ss, ax",
    "jmp fword ptr [far_ptr_flush]",
    "_start32_flush:",
    // PD_LOW: identity-map physical [0, 64 MiB) -- see this file's module doc comment for why this
    // window's size is a fixed constant while PD_HIGH's below is not.
    "mov edi, offset temp_pd_low",
    "xor eax, eax",
    "mov ecx, 32",
    "1:",
    "mov edx, eax",
    "or edx, 0x83", // PRESENT | WRITABLE | HUGE_PAGE
    "mov [edi], edx",
    "mov dword ptr [edi+4], 0",
    "add eax, 0x200000",
    "add edi, 8",
    "loop 1b",
    // PD_HIGH: map the real kernel image's own physical range [_kernel_phys_start,
    // _kernel_phys_end), sized dynamically -- never a hardcoded page count.
    "mov eax, offset _kernel_phys_end",
    "add eax, 0x1FFFFF",
    "shr eax, 21",
    "mov esi, offset _kernel_phys_start",
    "shr esi, 21",
    "sub eax, esi",
    "mov ecx, eax",
    "mov edi, offset temp_pd_high",
    "mov eax, offset _kernel_phys_start",
    "2:",
    "mov edx, eax",
    "or edx, 0x83",
    "mov [edi], edx",
    "mov dword ptr [edi+4], 0",
    "add eax, 0x200000",
    "add edi, 8",
    "loop 2b",
    // PDPT_LOW[0] -> PD_LOW
    "mov eax, offset temp_pd_low",
    "or eax, 0x03", // PRESENT | WRITABLE
    "mov [temp_pdpt_low], eax",
    "mov dword ptr [temp_pdpt_low+4], 0",
    // PDPT_HIGH[510] -> PD_HIGH (0xffffffff80000000 is exactly PDPT index 510)
    "mov eax, offset temp_pd_high",
    "or eax, 0x03",
    "mov [temp_pdpt_high + 510*8], eax",
    "mov dword ptr [temp_pdpt_high + 510*8 + 4], 0",
    // PML4[0] -> PDPT_LOW, PML4[511] -> PDPT_HIGH
    "mov eax, offset temp_pdpt_low",
    "or eax, 0x03",
    "mov [temp_pml4], eax",
    "mov dword ptr [temp_pml4+4], 0",
    "mov eax, offset temp_pdpt_high",
    "or eax, 0x03",
    "mov [temp_pml4 + 511*8], eax",
    "mov dword ptr [temp_pml4 + 511*8 + 4], 0",
    "mov eax, offset temp_pml4",
    "mov cr3, eax",
    "mov eax, cr4",
    "or eax, 1 << 5", // PAE
    "mov cr4, eax",
    "mov ecx, 0xC0000080", // IA32_EFER
    "rdmsr",
    "or eax, 1 << 8", // LME
    "wrmsr",
    "mov eax, cr0",
    "or eax, 1 << 31", // PG
    "mov cr0, eax",
    "jmp fword ptr [far_ptr_long_mode]",
    // --- Stage A tail: land in 64-bit long mode, hand off to Rust ---
    ".code64",
    ".global _start64_prelim",
    "_start64_prelim:",
    "mov ax, 0x10",
    "mov ds, ax",
    "mov es, ax",
    "mov fs, ax",
    "mov gs, ax",
    "mov ss, ax",
    "mov rsp, offset boot32_stack_top",
    // System V AMD64 requires RSP % 16 == 0 *at the point of a CALL instruction*, i.e. RSP % 16
    // == 8 immediately upon entry to a normal callee (after CALL's own implicit return-address
    // push). Landing here via a plain `jmp` (see below) never does that implicit push, so a
    // 16-aligned boot32_stack_top leaves RSP at the *wrong* parity for every call this trampoline
    // "enters" Rust as if it were one -- harmless for most code, but a real #GP the first time
    // anything needs genuine 16-byte alignment (found live: this crashed silently inside
    // cpu::fpu::init()'s `fxsave`, which faults on a misaligned operand).
    "sub rsp, 8",
    // System V AMD64: first two integer args in RDI/RSI. A plain 32-bit `mov` zero-extends into
    // the full 64-bit register, so this correctly zero-extends both u32 handoff values.
    "mov eax, [mb2_saved_magic]",
    "mov edi, eax",
    "mov eax, [mb2_saved_info_ptr]",
    "mov esi, eax",
    // Indirect jump through a register, not a direct `jmp multiboot2_rust_entry` -- the
    // displacement between this low trampoline code and the higher-half Rust entry point is right
    // at the edge of (and, depending on exact kernel size, potentially beyond) a `jmp rel32`'s
    // range, since the higher-half base is itself -2 GiB. `mov reg, imm64` always encodes as a
    // full 64-bit immediate (movabs), so this has no such range limit.
    "mov rax, offset multiboot2_rust_entry",
    "jmp rax",
);

/// Stage B: validates the Multiboot2 handoff, parses the memory map, builds and installs the real
/// final page tables, and returns a `&'static BootInfo` -- the exact point where this boot path
/// converges with `boot::read_boot_info()`'s own return value. Called by the
/// `multiboot2_entry_point!`-generated `multiboot2_rust_entry`, never directly.
///
/// # Safety
///
/// Must be called at most once, from `_start64_prelim` (or an equivalent caller that has already
/// installed Stage A's own temporary page tables) -- reads raw physical memory at `mbi_phys`
/// through the temporary identity mapping, and installs a brand new `CR3`.
pub unsafe fn init_from_mbi(magic: u32, mbi_phys: u32) -> &'static BootInfo {
    assert_eq!(
        magic, MULTIBOOT2_BOOTLOADER_MAGIC,
        "invalid Multiboot2 magic in EAX: {magic:#x} (expected {MULTIBOOT2_BOOTLOADER_MAGIC:#x})"
    );

    // Parse tags before touching CR3 again -- simplest to reach `mbi_phys` (a low physical
    // address) via Stage A's own still-active temporary tables rather than depend on ordering
    // relative to `install_final_page_tables` (whose own final tables happen to keep the same low
    // window mapped too -- see `temp_pdpt_low`'s own doc comment for why that turned out to be
    // required, not just convenient).
    let entries = unsafe { parse_mmap(mbi_phys as u64) };

    unsafe { install_final_page_tables() };

    static mut BOOT_INFO: Option<BootInfo> = None;
    unsafe {
        BOOT_INFO = Some(BootInfo {
            physical_memory_offset: MULTIBOOT2_HHDM_OFFSET,
            memory_map: entries,
        });
        (&raw const BOOT_INFO).as_ref().unwrap().as_ref().unwrap()
    }
}

/// Real ceiling on how many Multiboot2 memory-map entries this boot path can carry into
/// `BootInfo` -- generous for any real or QEMU x86_64 machine's own memory map (typically well
/// under 20 entries), documented rather than silently truncated without comment, matching this
/// file's `MULTIBOOT2_HHDM_CEILING_BYTES` precedent.
const MAX_MMAP_ENTRIES: usize = 64;

static mut MMAP_STORAGE: [Entry; MAX_MMAP_ENTRIES] = [const {
    Entry {
        base: 0,
        length: 0,
        type_: 0,
    }
}; MAX_MMAP_ENTRIES];
static mut MMAP_PTRS: [MaybeUninit<&'static Entry>; MAX_MMAP_ENTRIES] =
    [const { MaybeUninit::uninit() }; MAX_MMAP_ENTRIES];

/// Walks the Multiboot2 info structure at `mbi_phys` (spec section 3.4: a `total_size`/`reserved`
/// header followed by a sequence of 8-byte-aligned tags), keeping only the `MULTIBOOT_TAG_TYPE_MMAP`
/// tag's entries, translated into the exact `limine::memmap::Entry` shape
/// `memory::BootInfoFrameAllocator` already consumes unmodified.
///
/// # Safety
///
/// `mbi_phys` must be a physical address currently reachable through an active identity mapping
/// (true immediately after Stage A, via `temp_pd_low`), and this must not be called concurrently
/// with another call (writes shared `static mut` storage).
unsafe fn parse_mmap(mbi_phys: u64) -> &'static [&'static Entry] {
    let base = mbi_phys as usize;
    // SAFETY: per this function's own contract, `base` is identity-mapped right now.
    let total_size = unsafe { (base as *const u32).read_unaligned() } as usize;

    let mut offset = 8usize; // skip the { total_size, reserved } header
    let mut count = 0usize;
    while offset + 8 <= total_size {
        let tag_addr = base + offset;
        // SAFETY: tag_addr is within [base, base + total_size), which the Multiboot2 spec
        // guarantees the loader made available starting at mbi_phys.
        let typ = unsafe { (tag_addr as *const u32).read_unaligned() };
        let size = unsafe { ((tag_addr + 4) as *const u32).read_unaligned() } as usize;
        if typ == TAG_TYPE_END {
            break;
        }
        if typ == TAG_TYPE_MMAP && size >= 16 {
            let entry_size = unsafe { ((tag_addr + 8) as *const u32).read_unaligned() } as usize;
            if entry_size > 0 {
                let entries_base = tag_addr + 16;
                let entry_count = (size - 16) / entry_size;
                for i in 0..entry_count {
                    if count >= MAX_MMAP_ENTRIES {
                        break;
                    }
                    let entry_addr = entries_base + i * entry_size;
                    // SAFETY: entry_addr is within this same tag's own [tag_addr, tag_addr+size).
                    let mb_base = unsafe { (entry_addr as *const u64).read_unaligned() };
                    let mb_length = unsafe { ((entry_addr + 8) as *const u64).read_unaligned() };
                    let mb_type = unsafe { ((entry_addr + 16) as *const u32).read_unaligned() };
                    // SAFETY: count < MAX_MMAP_ENTRIES, checked above; no other code touches
                    // MMAP_STORAGE concurrently (see this function's own safety contract).
                    unsafe {
                        (&raw mut MMAP_STORAGE)
                            .cast::<Entry>()
                            .add(count)
                            .write(Entry {
                                base: mb_base,
                                length: mb_length,
                                type_: translate_mmap_type(mb_type),
                            });
                    }
                    count += 1;
                }
            }
        }
        // Every tag is padded to an 8-byte boundary (spec section 3.4).
        offset += (size + 7) & !7;
    }

    // SAFETY: entries [0, count) were just written above; no aliasing &mut exists.
    unsafe {
        for i in 0..count {
            let entry_ref: &'static Entry = &*(&raw const MMAP_STORAGE).cast::<Entry>().add(i);
            MMAP_PTRS[i].write(entry_ref);
        }
        core::slice::from_raw_parts((&raw const MMAP_PTRS).cast::<&'static Entry>(), count)
    }
}

fn translate_mmap_type(mb_type: u32) -> u64 {
    match mb_type {
        MULTIBOOT_MEMORY_AVAILABLE => MEMMAP_USABLE,
        MULTIBOOT_MEMORY_ACPI_RECLAIMABLE => MEMMAP_ACPI_RECLAIMABLE,
        MULTIBOOT_MEMORY_NVS => MEMMAP_ACPI_NVS,
        MULTIBOOT_MEMORY_BADRAM => MEMMAP_BAD_MEMORY,
        // MULTIBOOT_MEMORY_RESERVED (2) and anything this spec version doesn't define yet both
        // land here -- MEMMAP_RESERVED is the safe default (never treated as usable).
        _ => MEMMAP_RESERVED,
    }
}

static mut FINAL_PML4: PageTable = PageTable::new();
static mut HHDM_PDPT: PageTable = PageTable::new();
static mut HHDM_PDS: [PageTable; HHDM_PD_COUNT] = [const { PageTable::new() }; HHDM_PD_COUNT];

/// `MULTIBOOT2_HHDM_OFFSET`'s own PML4 index (256 -- see this constant's own value: exactly
/// `256 * 512 GiB`).
const HHDM_PML4_INDEX: usize = 256;
/// `KERNEL_HIGHER_HALF_BASE`'s own PML4 index (511 -- the same "topmost 2 GiB" slot the
/// plain-Limine kernel script's own comment names).
const KERNEL_PML4_INDEX: usize = 511;
/// Stage A's own low-identity window's PML4 index (0) -- see `temp_pdpt_low`'s own doc comment
/// above for why the final tables must keep this mapped too, not just the temporary ones.
const LOW_IDENTITY_PML4_INDEX: usize = 0;

/// Builds the real, final page tables: a fresh `MULTIBOOT2_HHDM_OFFSET`-based window covering
/// `MULTIBOOT2_HHDM_CEILING_BYTES` of physical memory (this boot path's own HHDM), plus the exact
/// same kernel-higher-half *and* low-identity mappings Stage A's temporary tables already built
/// (both reused directly, not rebuilt -- their content never changes). The low-identity window is
/// *not* optional to keep, even though the fresh HHDM window below also covers all of physical
/// memory, low addresses included -- see `temp_pdpt_low`'s own doc comment for why (the
/// currently-running stack lives there).
///
/// # Safety
///
/// Must run with Stage A's own temporary tables still active (this function's own writes to
/// `FINAL_PML4`/`HHDM_PDPT`/`HHDM_PDS` rely on the temporary kernel-higher-half alias still
/// mapping this crate's own `.bss`), and must be called at most once.
unsafe fn install_final_page_tables() {
    let kernel_phys_start = (&raw const _kernel_phys_start) as u64;
    let kernel_phys_end = (&raw const _kernel_phys_end) as u64;
    assert!(
        (kernel_phys_end - kernel_phys_start).div_ceil(HUGE_PAGE_SIZE) <= 512,
        "kernel image ({} bytes) exceeds the single-PD-table (1 GiB) ceiling this boot path's \
         temporary/final page tables assume",
        kernel_phys_end - kernel_phys_start
    );

    // SAFETY: per this function's own contract, these statics are reachable right now through
    // Stage A's still-active temporary kernel-higher-half alias.
    let hhdm_pds = unsafe { &mut *(&raw mut HHDM_PDS) };
    for (pd_index, pd) in hhdm_pds.iter_mut().enumerate() {
        for (entry_index, entry) in pd.iter_mut().enumerate() {
            let phys = (pd_index as u64) * ONE_GIB + (entry_index as u64) * HUGE_PAGE_SIZE;
            entry.set_addr(
                PhysAddr::new(phys),
                PageTableFlags::PRESENT | PageTableFlags::WRITABLE | PageTableFlags::HUGE_PAGE,
            );
        }
    }

    let hhdm_pdpt = unsafe { &mut *(&raw mut HHDM_PDPT) };
    for (i, pd) in hhdm_pds.iter().enumerate() {
        let pd_phys = kernel_virt_to_phys(pd as *const PageTable as u64);
        hhdm_pdpt[i].set_addr(
            PhysAddr::new(pd_phys),
            PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
        );
    }

    let final_pml4 = unsafe { &mut *(&raw mut FINAL_PML4) };
    let hhdm_pdpt_phys = kernel_virt_to_phys(hhdm_pdpt as *const PageTable as u64);
    final_pml4[HHDM_PML4_INDEX].set_addr(
        PhysAddr::new(hhdm_pdpt_phys),
        PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
    );
    // `temp_pdpt_high` lives in `.boot32.data`, which -- unlike this crate's own ordinary
    // `.bss` -- has VMA == LMA (see x86_64-oxidebsd-multiboot2.ld), so its own address already
    // *is* its physical address; no kernel_virt_to_phys translation for this one.
    let temp_pdpt_high_phys = (&raw const temp_pdpt_high) as u64;
    final_pml4[KERNEL_PML4_INDEX].set_addr(
        PhysAddr::new(temp_pdpt_high_phys),
        PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
    );
    // See temp_pdpt_low's own doc comment above: the low-identity window has to survive into the
    // final tables too, since the currently-running stack lives inside it.
    let temp_pdpt_low_phys = (&raw const temp_pdpt_low) as u64;
    final_pml4[LOW_IDENTITY_PML4_INDEX].set_addr(
        PhysAddr::new(temp_pdpt_low_phys),
        PageTableFlags::PRESENT | PageTableFlags::WRITABLE,
    );

    let final_pml4_phys = kernel_virt_to_phys(final_pml4 as *const PageTable as u64);
    let (_, flags) = Cr3::read();
    unsafe {
        Cr3::write(
            PhysFrame::containing_address(PhysAddr::new(final_pml4_phys)),
            flags,
        );
    }
}

/// Drop-in Multiboot2 counterpart to `limine_entry_point!` -- same two-line-per-call-site shape,
/// same `fn(&'static BootInfo) -> !` calling convention for `$path`, so a `tests/*.rs` file's own
/// `main` needs no changes to run under either boot path.
#[macro_export]
macro_rules! multiboot2_entry_point {
    ($path:path) => {
        #[unsafe(no_mangle)]
        extern "C" fn multiboot2_rust_entry(magic: u32, mbi_phys: u32) -> ! {
            let boot_info: &'static $crate::boot::BootInfo =
                unsafe { $crate::boot::multiboot2::init_from_mbi(magic, mbi_phys) };
            let f: fn(&'static $crate::boot::BootInfo) -> ! = $path;
            f(boot_info)
        }
    };
}
