.Dd September 26, 2026
.Dt FOO 1
.Os OxideBSD
.Sh NAME
.Nm foo
.Nd do a thing
.Sh SYNOPSIS
.Nm
.Op Fl ab
.Op Fl c Ar file
.Ar arg ...
.Sh DESCRIPTION
The
.Nm
utility does things. It is nice.
Another sentence here that is quite long and should wrap around the right margin at some point, let us see.
.Pp
Second paragraph.
.Bl -tag -width indent
.It Fl a
Alpha.
.It Fl longer
Longer tag than width.
.El
.Sh SEE ALSO
.Xr bar 1
