.Dd September 26, 2026
.Dt FOO 1
.Os
.Sh DESCRIPTION
em\(em en\(en hy\(hy lq\(lqrq\(rq oq\(oqcq\(cq aq\(aq dq\(dq bu\(bu co\(co \e \- \&. a\ b a\~b
.Dq quoted
.Sq single
.Ql literal
.Pa /etc/foo ,
.Ev PATH .
.Em emph
.Sy sym
.Li lit
.Dv FOO
.Er EINTR
Text with \fBbold\fR and \fIital\fP here.
.Pp
.Op Fl a | Fl b
.Ic cmd Ar x Ns = Ns Ar y
.Xr a 1 ,
.Xr b 2
and
.Xr c 3 .
