.TH BAR 8 2024-01-02
.SH DESCRIPTION
Before.
.RS
Default rs.
.RE
.TP
.B \-\-very\-long\-option
Body after long tag.
.TP
.B \-x
Short.
.PP
.IP
No tag ip.
.IP x 10
wide.
.RS 3
rs3
.RE
.PP
Para
.br
after br
.sp
after sp
.SH "QUOTED HEAD"
.SS
Sub on next line
text
.SH
Head on next line
body
.PP
\fBbold\fP and \fIital\fP and \f(BIboth\fR.
.SM small
.SB smallbold
.B
next line bold
.I
