.Dd x
.Dt X 1
.Os T
.Sh SEE ALSO
.Xr a 1
.Rs
.%T Secure Hash Standard
.%R FIPS PUB 180-2
.Re
.Rs
.%A Alice A
.%A Bob B
.%A Carol C
.%T "An article"
.%J Journal of Things
.%V 12
.%N 3
.%P 1-10
.%I Publisher
.%C City
.%D 2001
.%O note
.%U https://x.y
.%Q Corp
.%B Book Title
.Re
.Sh DESCRIPTION
Inline
.Rs
.%A Only One
.%B Book
.Re
text.
