.Dd x
.Dt F 3
.Os T
.Sh NAME
.Nm f
.Nd g
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdio.h
.In sys/types.h
.Ft int
.Fn printf "const char *fmt" ...
.Ft struct archive *
.Fn archive_read_new void
.Fn noft int
.Ft void
.Fo longfunc
.Fa "int a"
.Fa "char *b"
.Fc
.Vt extern int errno ;
.Fd #define X 1
.Sh DESCRIPTION
Call
.Fn printf "const char *" int
and
.Fn g
or
.Fo h
.Fa x
.Fc .
.Ft int
in text.
.Va var
.In foo.h
.Sh RETURN VALUES
.Rv -std f g
.Sh AUTHORS
.An -nosplit
.An A B Aq Mt a@b.c
and
.An C D .
.Lk https://example.org Example
.Lk https://example.org
.Mt x@y.z
