//! How much each system call costs: a count, the wall time and the CPU time per call number,
//! for every call made from user space, read as `debug.syscall.stats` and zeroed with
//! `debug.syscall.reset` (sysctl(8)). Interrupts are masked for a whole system call, so a timer
//! sampling profiler can't see inside one; this measures instead, with the TSC at entry and
//! exit. Wall time includes time spent blocked (a `wait4` waiting for its child); CPU time
//! subtracts what the process spent switched out meanwhile (`OFF_CPU`, which the scheduler keeps
//! for the running process), leaving the kernel's own work. Calls the kernel makes to itself
//! (exec reading its file through `read`) are part of the outer call, not counted again.

use alloc::vec::Vec;
use core::fmt::Write;
use core::sync::atomic::{AtomicU64, Ordering};

/// Call numbers counted; larger ones (the test-only 9997-9999) aren't.
const MAX: usize = 1024;

const ZERO: AtomicU64 = AtomicU64::new(0);
static COUNT: [AtomicU64; MAX] = [ZERO; MAX];
static WALL: [AtomicU64; MAX] = [ZERO; MAX];
static CPU: [AtomicU64; MAX] = [ZERO; MAX];

/// TSC cycles the running process has spent switched out since it was created; the scheduler
/// saves it with the outgoing process and restores the incoming one's (plus the time it was out).
pub static OFF_CPU: AtomicU64 = AtomicU64::new(0);

/// The names, from musl's `bits/syscall.h.in` (generated by build.rs): `(number, name)`.
static NAMES: &[(u16, &str)] = include!(concat!(env!("OUT_DIR"), "/syscall_names.rs"));

fn name(nr: usize) -> &'static str {
    NAMES.iter().find(|&&(n, _)| n as usize == nr).map_or("?", |&(_, s)| s)
}

/// The TSC and the off-CPU count at a call's entry.
#[derive(Clone, Copy)]
pub struct Start {
    tsc: u64,
    off: u64,
}

pub fn start() -> Start {
    Start { tsc: crate::cpu::tsc::now(), off: OFF_CPU.load(Ordering::Relaxed) }
}

/// Records call `nr`, which began at `s`.
pub fn record(nr: u64, s: Start) {
    let nr = nr as usize;
    if nr >= MAX {
        return;
    }
    let wall = crate::cpu::tsc::now().saturating_sub(s.tsc);
    let off = OFF_CPU.load(Ordering::Relaxed).saturating_sub(s.off);
    COUNT[nr].fetch_add(1, Ordering::Relaxed);
    WALL[nr].fetch_add(wall, Ordering::Relaxed);
    CPU[nr].fetch_add(wall.saturating_sub(off), Ordering::Relaxed);
}

/// The phases of `execve` (`lifecycle::exec_image`), timed separately: where an exec's time goes.
pub const EXEC_PHASES: [&str; 8] =
    ["read file", "parse, new space", "load ELF", "load interpreter", "stack", "switch over", "free old space", "close, cleanup"];
static PHASE: [AtomicU64; 8] = [ZERO; 8];
static EXECS: AtomicU64 = AtomicU64::new(0);

/// Adds the time between successive TSC `marks` (one more than the phases) to each phase.
pub fn exec_phases(marks: &[u64; 9]) {
    EXECS.fetch_add(1, Ordering::Relaxed);
    for i in 0..8 {
        PHASE[i].fetch_add(marks[i + 1].saturating_sub(marks[i]), Ordering::Relaxed);
    }
}

pub fn reset() {
    EXECS.store(0, Ordering::Relaxed);
    for p in &PHASE {
        p.store(0, Ordering::Relaxed);
    }
    for i in 0..MAX {
        COUNT[i].store(0, Ordering::Relaxed);
        WALL[i].store(0, Ordering::Relaxed);
        CPU[i].store(0, Ordering::Relaxed);
    }
}

/// The table, most CPU time first: number, name, calls, wall and CPU milliseconds, CPU
/// microseconds per call.
pub fn report() -> Vec<u8> {
    let us = crate::cpu::tsc::cycles_to_us;
    let mut rows: Vec<(usize, u64, u64, u64)> = (0..MAX)
        .filter_map(|i| {
            let n = COUNT[i].load(Ordering::Relaxed);
            (n > 0).then(|| (i, n, WALL[i].load(Ordering::Relaxed), CPU[i].load(Ordering::Relaxed)))
        })
        .collect();
    rows.sort_by(|a, b| b.3.cmp(&a.3));
    let mut out = alloc::string::String::new();
    let _ = writeln!(out, "\n  nr name                    calls     wall ms      cpu ms  cpu us/call");
    for (nr, n, wall, cpu) in rows {
        let _ = writeln!(
            out,
            "{:4} {:<20} {:>8} {:>11} {:>11} {:>12}",
            nr,
            name(nr),
            n,
            us(wall) / 1000,
            us(cpu) / 1000,
            us(cpu) / n
        );
    }
    let execs = EXECS.load(Ordering::Relaxed);
    if execs > 0 {
        let _ = writeln!(out, "\n  execve, by phase ({execs} completed):        total ms   us/exec");
        for (i, name) in EXEC_PHASES.iter().enumerate() {
            let t = us(PHASE[i].load(Ordering::Relaxed));
            let _ = writeln!(out, "       {:<30} {:>11} {:>9}", name, t / 1000, t / execs);
        }
    }
    out.into_bytes()
}
